// vue/src/App.vue
<template>
  <div>
    <h1>Vue</h1>

    <UI-Button icon="add" label="Adicionar" color="rgb(100, 122, 152)" @click="$refs.uiModal.open()">
    </UI-Button>

    <br />

    <UI-InputField
      disabled="false"
      value="Senha123@"
      type="type"
      label="Nome:"
      placeholder="Digite seu nome aqui."
      border-color="rgb(100, 122, 152)"
    >
    </UI-InputField>

    <br />

    <UI-Dropdown
      selected="Brasil"
      disabled="true"
      label="País:"
      options='["Brasil", "Argentina" , "Chile" ]'
      border-color="rgb(100, 122, 152)"
    >
    </UI-Dropdown>

    <br />

    <UI-Modal
      ref="uiModal"
      color="rgb(100, 122, 152)"
      title="Salvar mudanças?"
      message="Depois de salvar, as mudanças não poderão ser desfeitas."
    >
    </UI-Modal>

    <br />

    <UI-Card
      image="https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
      title="Tênis Nike Fit 2.0"
      color="white"
      title-color="black"
      description-color="black"
      description="Esse tênis é perfeito para você que gosta de correr. Ele tem um design moderno e é super confortável."
    >
    </UI-Card>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { UIButton, UIInputField, UIDropdown, UIModal, UICard } from 'ui-library'

export default defineComponent({
  setup() {
    return {
      components: {
        UIButton,
        UIInputField,
        UIDropdown,
        UIModal,
        UICard,
      }
    }
  },
})
</script>

// angular/src/app/app.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AppComponent {
  title = 'angular';
}

<div>
  <h1>Angular</h1>

  <UI-Button icon="add" label="Adicionar" color="rgb(100, 122, 152)">
  </UI-Button>

  <br />

  <UI-InputField disabled="false" value="Senha123@" type="type" label="Nome:" placeholder="Digite seu nome aqui."
    border-color="rgb(100, 122, 152)">
  </UI-InputField>

  <br />

  <UI-Dropdown selected="Brasil" disabled="true" label="País:" options='["Brasil", "Argentina" , "Chile" ]'
    border-color="rgb(100, 122, 152)">
  </UI-Dropdown>

  <br />

  <UI-Modal color="rgb(100, 122, 152)" title="Salvar mudanças?"
    message="Depois de salvar, as mudanças não poderão ser desfeitas.">
  </UI-Modal>

  <br />

  <UI-Card
    image="https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    title="Tênis Nike Fit 2.0" color="white" title-color="black" description-color="black"
    description="Esse tênis é perfeito para você que gosta de correr. Ele tem um design moderno e é super confortável.">
  </UI-Card>
</div>
